[package]
name = "BassieTest"
identifier = "nl.plaatsoft.BassieTest"
version = "0.1.0"

[build]
ldflags = "-framework Cocoa"

[package.metadata.bundle]
lipo = true
copyright = "Copyright Â© 2022-2025 Bastiaan van der Plaat"
